### ISSUE TITLE
Change the database us_dollar column from bigdecimal to floating point

### ISSUE THREAD

**Issue by kmossco** [kmossco/exchange_rates_converter#3]
`ExchangeRate.create(date: Date.today, us_dollar: 3)`

returns

```ruby
<ExchangeRate:0x00007f820239c110
 id: nil,
 date: Fri, 01 Jun 2018,
 us_dollar: 0.3e1,
 created_at: nil,
 updated_at: nil>
```

`_.us_dollar.to_f = 3.0`

This is happening because I initially set the database schema to BigDecimal to ensure floating point precision. But the data sources don't really benefit from it, and changing to float would make it easier to parse and manipulate the data.

**Comment by vicentllongo** [comment]
This is what I get in the rails console:
```ruby
er = ExchangeRate.create(date: Date.today, us_dollar: 1.2345)
er.us_dollar
=> 1
er.us_dollar.class.name
=> "Fixnum" 
```

Using:
ruby: 2.5
OS X: 10.13.2
sqlite: 3.19.3

**Comment by kmossco** [comment]
Really seems like the problem is using the BigDecimal type for the column, changing it to Float worked for me using your code:

```ruby
er = ExchangeRate.create(date: Date.today - 1, us_dollar: 1.2345)
er.us_dollar
=> 1.2345
er.us_dollar.class.name
=> "Float"
```

Changing that type seems to do the trick, but want to be sure by adding a spec specifically for this in the model. 👍
